### ISSUE TITLE
How to download older soem versions

### ISSUE THREAD

**Issue by mictas** [mgruhler/soem#32]
Hello,

we are following with great interest this SOEM ROS package.
Before starting to use v.1.4.0 we still need to finish some tests with the previous version 1.3.0.
We need to install it on a new pc but we suppose that the "Installation" instructions are referred to the newer version (v1.4.0).
I'm sorry for my trivial question, but how can we download and install v.1.3.0 with a "sudo apt-get ..." command?
Waiting for your response, thank you.
Best regards.

**Comment by mgruhler** [comment]
@mictas 
Seems that the ROS package repos only keep the latest version. So there is no way to downgrade with `apt`.

I'd suggest to build it from source (check out the v1.3.0 tag!) in a underlay workspace, call `catkin_make install` and use the respective install space as basis for your overlay, as discussed [in the Readme](https://github.com/mgruhler/soem/blob/dc0f6ed153aaa3f9310c5d1a12cc0090f770c155/README.md#Development).
