### ISSUE TITLE
Hardware needed?

### ISSUE THREAD

**Issue by cowboygary** [mgruhler/soem#35]
Hi @mgruhler,

I want to communicate my PC to an Ethercat remote IO using ROS.

Do I need special chip on the PC side?
Or I can directly communicate using soem?

**Comment by mgruhler** [comment]
No, you don't need any special hardware. I've done this e.g. using a RPi3 running Ubuntu Mate or an Intel Nuc with a regular Ubuntu.

You obviously do need an Ethernet jack though.

**Comment by cowboygary** [comment]
Thanks @mgruhler 

I will try it and will share here if it is successful.
