### ISSUE TITLE
ROS Noetic release

### ISSUE THREAD

**Issue by Olavhaasie** [mgruhler/soem#37]
**Question**
Are you planning on making a release for ROS Noetic?

**Comment by mgruhler** [comment]
Yes, a release would be the right thing to do. I don't have a noetic machine at the moment, though. So I don't know when I'll get around to test that.

As this is pretty much cmake only, I guess this should be a piece of cake, though...

**Comment by Olavhaasie** [comment]
I was able to successfully build the master branch on ROS Noetic without any changes. However, the [Noetic migration guide](https://wiki.ros.org/noetic/Migration#Increase_required_CMake_version_to_avoid_author_warning) suggest upgrading minimum CMake version to 3.0.2.

**Comment by mgruhler** [comment]
@Olavhaasie thank you for your patience.

See ros/rosdistro#25540.

Please report back if you experience any issues.
