### ISSUE TITLE
FSOE SOEM management

### ISSUE THREAD

**Issue by mictas** [mgruhler/soem#44]
Hello,

we use this "SOEM ROS package" to manage our actuators (ROS Melodic - Ubuntu 18.04 LTS). It works.
For a future project we need to manage Safety funtions using FSOE. A commercial device will act as "Master FSOE" and "EtherCAT Slave". We suppose that "SOEM ROS" should be able to manage "EtherCAT" data and "FSOE" data using different PDOs. 
Is the current "SOEM ROS" package able to manage FSOE data?
If not, is someone developing it?

I found the following page in github:

https://github.com/rtlabs-com/fsoe-soem-demo

Waiting for a response, thank you.
Best regards.

**Comment by mgruhler** [comment]
Hi @mictas ,

I don't know about FSOE or its requirements. So I guess you are better of with asking this at the [original SOEM repo](https://github.com/OpenEtherCATsociety/SOEM) and have a look at maybe [this issue there](https://github.com/OpenEtherCATsociety/SOEM/issues/257). Please remember that this repo merely wraps the original SOEM code into a catkin package...
Thus, I'll close this issue, as this is a question about the capabilities of SOEM, not the ROS SOEM wrapper.

As a side note, I've now closed your issue #43 . I consider this answered as there has been no further feedback from you...
