### ISSUE TITLE
how to install  soem on xenomai 

### ISSUE THREAD

**Issue by wujinghust** [mgruhler/soem#6]
To compile for linux:

go to project directory

source ./setup.sh linux

make all

when I input make all in terminal 

there are serveal  error as fellow 

--- Compiling ebox.c
ebox.c: In function ‘eboxtest’:
ebox.c:196:26: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64’ [-Wformat]
ebox.c: In function ‘ecatthread’:
ebox.c:284:8: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
ebox.c: In function ‘main’:
ebox.c:348:8: warning: variable ‘iret1’ set but not used [-Wunused-but-set-variable]
--- Linking ebox
/usr/bin/ld: cannot find -lsoem
collect2: ld returned 1 exit status
make[3]: **\* [ebox] Error 1
make[2]: **\* [subdirs] Error 2
make[1]: **\* [linux] Error 2
make: **\* [test] Error 2

**Comment by mgruhler** [comment]
This seems to be more about the the original SOEM, and not the ROS package.
If this problem still exists (I know, very old issue), check at https://github.com/OpenEtherCATsociety/SOEM
