### ISSUE TITLE
compile the soem library

### ISSUE THREAD

**Issue by wujinghust** [mgruhler/soem#7]
when I make the makefile in soem directory, there is a error as fellow:

make: **\* No rule to make target `simple_test.o', needed by`simple_test'.  Stop.

what should I do ? thank for you help。

**Comment by smits** [comment]
Depending on what you exactly want to do you could also take a look at the
official repos and see if it is fixed there:
https://github.com/OpenEtherCATsociety/SOEM
This repos is a fork that is typically build as part of a catkin workspace
and uses cmake instead of the original instructions.

On Fri, Feb 26, 2016 at 12:03 PM wujinghust <notifications@github.com>
wrote:

> when I make the makefile in soem directory, there is a error as fellow:
>
> make: *** No rule to make target simple_test.o', needed bysimple_test'.
> Stop.
>
> what should I do ? thank for you help。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smits/soem/issues/7>.
>
-- 
Ruben Smits, Roboticist - Founder
+32 479 511 786
Intermodalics - Kapeldreef 60, 3001 Heverlee - BELGIUM
www.intermodalics.eu

**Comment by wujinghust** [comment]
thanks for you help ! 
I copy oshw.c oshw.h osal.h osal.c nicdrv.c nicdrv.h to the soem directory, and I modify the makefile.
but there are errors when I compile the makefile .

make: Circular simple_test.o <- simple_test.o dependency dropped.
gcc -O2 -lpthread -lm -lrt -lc -lpq -Wall -o ethercatconfig.o ethercatconfig.c ethercatconfig.h ethercatcoe.c ethercatcoe.h ethercattype.h osal.c osal.h oshw.h oshw.c ethercatmain.c ethercatmain.h ethercatbase.c ethercatbase.h ethercatsoe.h ethercatsoe.c
In file included from oshw.h:29:0,
                 from ethercatconfig.c:52:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
ethercatconfig.h:66:21: error: unknown type name ‘ecx_contextt’
ethercatconfig.h:66:44: error: unknown type name ‘uint8’
ethercatconfig.h:67:26: error: unknown type name ‘ecx_contextt’
ethercatconfig.h:67:63: error: unknown type name ‘uint8’
ethercatconfig.h:68:23: error: unknown type name ‘ecx_contextt’
ethercatconfig.h:68:46: error: unknown type name ‘uint16’
ethercatconfig.h:69:24: error: unknown type name ‘ecx_contextt’
ethercatconfig.h:69:47: error: unknown type name ‘uint16’
In file included from oshw.h:29:0,
                 from ethercatcoe.c:51:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
ethercatcoe.h:64:4: error: unknown type name ‘uint16’
ethercatcoe.h:66:4: error: unknown type name ‘uint16’
ethercatcoe.h:68:4: error: unknown type name ‘uint16’
ethercatcoe.h:70:4: error: unknown type name ‘uint16’
ethercatcoe.h:72:4: error: unknown type name ‘uint8’
ethercatcoe.h:74:4: error: unknown type name ‘uint8’
ethercatcoe.h:76:31: error: ‘EC_MAXNAME’ undeclared here (not in a function)
ethercatcoe.h:83:4: error: unknown type name ‘uint16’
ethercatcoe.h:85:4: error: unknown type name ‘uint8’
ethercatcoe.h:87:4: error: unknown type name ‘uint16’
ethercatcoe.h:89:4: error: unknown type name ‘uint16’
ethercatcoe.h:91:4: error: unknown type name ‘uint16’
ethercatcoe.h:112:19: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:112:42: error: unknown type name ‘uint16’
ethercatcoe.h:112:56: error: unknown type name ‘uint16’
ethercatcoe.h:112:70: error: unknown type name ‘uint8’
ethercatcoe.h:112:84: error: unknown type name ‘int32’
ethercatcoe.h:113:17: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:113:40: error: unknown type name ‘uint16’
ethercatcoe.h:113:54: error: unknown type name ‘uint16’
ethercatcoe.h:113:68: error: unknown type name ‘uint8’
ethercatcoe.h:114:23: error: unknown type name ‘boolean’
ethercatcoe.h:115:18: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:115:41: error: unknown type name ‘uint16’
ethercatcoe.h:115:55: error: unknown type name ‘uint16’
ethercatcoe.h:115:69: error: unknown type name ‘uint8’
ethercatcoe.h:116:5: error: unknown type name ‘boolean’
ethercatcoe.h:117:15: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:117:38: error: unknown type name ‘uint16’
ethercatcoe.h:117:52: error: unknown type name ‘uint16’
ethercatcoe.h:118:15: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:118:38: error: unknown type name ‘uint16’
ethercatcoe.h:118:52: error: unknown type name ‘uint16’
ethercatcoe.h:119:20: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:119:43: error: unknown type name ‘uint16’
ethercatcoe.h:120:22: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:120:45: error: unknown type name ‘uint16’
ethercatcoe.h:121:20: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:121:43: error: unknown type name ‘uint16’
ethercatcoe.h:122:27: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:122:50: error: unknown type name ‘uint16’
ethercatcoe.h:123:22: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:123:45: error: unknown type name ‘uint16’
ethercatcoe.h:123:58: error: unknown type name ‘uint8’
ethercatcoe.h:124:16: error: unknown type name ‘ecx_contextt’
ethercatcoe.h:124:39: error: unknown type name ‘uint16’
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
osal.c:24:18: fatal error: osal.h: No such file or directory
compilation terminated.
In file included from oshw.h:29:0:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
In file included from oshw.h:29:0,
                 from oshw.c:28:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
In file included from oshw.h:29:0,
                 from ethercatmain.c:56:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
ethercatmain.h:86:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:88:4: error: unknown type name ‘uint32’
ethercatmain.h:99:1: error: unknown type name ‘PACKED_END’
ethercatmain.h:103:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:103:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:86:16: note: originally defined here
ethercatmain.h:105:4: error: unknown type name ‘uint16’
ethercatmain.h:109:1: error: unknown type name ‘PACKED_END’
ethercatmain.h:112:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:112:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:103:16: note: originally defined here
ethercatmain.h:114:4: error: unknown type name ‘uint16’
ethercatmain.h:137:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:140:4: error: unknown type name ‘uint16’
ethercatmain.h:271:4: error: unknown type name ‘uint32’
ethercatmain.h:273:4: error: unknown type name ‘uint32’
ethercatmain.h:275:4: error: unknown type name ‘uint8’
ethercatmain.h:277:4: error: unknown type name ‘uint32’
ethercatmain.h:279:4: error: unknown type name ‘uint8’
ethercatmain.h:281:4: error: unknown type name ‘boolean’
ethercatmain.h:283:4: error: unknown type name ‘uint16’
ethercatmain.h:285:4: error: unknown type name ‘int16’
ethercatmain.h:287:4: error: unknown type name ‘uint8’
ethercatmain.h:289:4: error: unknown type name ‘uint16’
ethercatmain.h:291:4: error: unknown type name ‘uint16’
ethercatmain.h:293:4: error: unknown type name ‘uint16’
ethercatmain.h:295:4: error: unknown type name ‘uint16’
ethercatmain.h:297:4: error: unknown type name ‘uint16’
ethercatmain.h:299:4: error: unknown type name ‘boolean’
ethercatmain.h:301:4: error: unknown type name ‘uint32’
ethercatmain.h:307:4: error: unknown type name ‘uint16’
ethercatmain.h:308:4: error: unknown type name ‘uint8’
ethercatmain.h:309:4: error: unknown type name ‘uint8’
ethercatmain.h:310:4: error: unknown type name ‘uint8’
ethercatmain.h:311:4: error: unknown type name ‘uint8’
ethercatmain.h:312:4: error: unknown type name ‘uint8’
ethercatmain.h:318:4: error: unknown type name ‘uint16’
ethercatmain.h:319:4: error: unknown type name ‘uint8’
ethercatmain.h:320:4: error: unknown type name ‘uint16’
ethercatmain.h:321:4: error: unknown type name ‘uint16’
ethercatmain.h:322:4: error: unknown type name ‘uint8’
ethercatmain.h:323:4: error: unknown type name ‘uint8’
ethercatmain.h:324:4: error: unknown type name ‘uint8’
ethercatmain.h:325:4: error: unknown type name ‘uint8’
ethercatmain.h:331:4: error: unknown type name ‘uint16’
ethercatmain.h:332:4: error: unknown type name ‘uint16’
ethercatmain.h:333:4: error: unknown type name ‘uint16’
ethercatmain.h:334:4: error: unknown type name ‘uint16’
ethercatmain.h:335:4: error: unknown type name ‘uint16’
ethercatmain.h:336:4: error: unknown type name ‘uint16’
ethercatmain.h:337:4: error: unknown type name ‘uint16’
ethercatmain.h:341:1: error: unknown type name ‘uint8’
ethercatmain.h:345:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:345:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:112:16: note: originally defined here
ethercatmain.h:347:4: error: unknown type name ‘uint16’
ethercatmain.h:352:1: error: unknown type name ‘PACKED_END’
ethercatmain.h:356:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:356:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:345:16: note: originally defined here
ethercatmain.h:358:4: error: unknown type name ‘uint16’
ethercatmain.h:365:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:367:4: error: unknown type name ‘uint8’
ethercatmain.h:377:4: error: unknown type name ‘int16’
ethercatmain.h:378:4: error: unknown type name ‘int16’
ethercatmain.h:379:4: error: unknown type name ‘ec_errort’
ethercatmain.h:384:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:384:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:356:16: note: originally defined here
ethercatmain.h:386:4: error: unknown type name ‘uint8’
ethercatmain.h:390:1: error: unknown type name ‘PACKED_END’
ethercatmain.h:394:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:394:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:384:16: note: originally defined here
ethercatmain.h:396:4: error: unknown type name ‘uint8’
ethercatmain.h:400:1: error: unknown type name ‘PACKED_END’
ethercatmain.h:404:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:404:16: error: redefinition of ‘struct PACKED’
ethercatmain.h:394:16: note: originally defined here
ethercatmain.h:406:4: error: unknown type name ‘uint8’
ethercatmain.h:413:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatmain.h:416:4: error: unknown type name ‘ecx_portt’
ethercatmain.h:510:1: error: unknown type name ‘uint8’
ethercatmain.h:510:21: error: unknown type name ‘uint8’
ethercatmain.h:512:1: error: unknown type name ‘ec_errort’
ethercatmain.h:513:1: error: unknown type name ‘boolean’
ethercatmain.h:513:45: error: unknown type name ‘ec_errort’
ethercatmain.h:514:1: error: unknown type name ‘boolean’
ethercatmain.h:515:45: error: unknown type name ‘uint16’
ethercatmain.h:515:59: error: unknown type name ‘uint16’
ethercatmain.h:515:73: error: unknown type name ‘uint8’
ethercatmain.h:515:87: error: unknown type name ‘uint16’
ethercatmain.h:517:47: error: unknown type name ‘ecx_redportt’
ethercatmain.h:519:1: error: unknown type name ‘uint8’
ethercatmain.h:519:45: error: unknown type name ‘uint16’
ethercatmain.h:519:59: error: unknown type name ‘uint16’
ethercatmain.h:520:1: error: unknown type name ‘int16’
ethercatmain.h:520:42: error: unknown type name ‘uint16’
ethercatmain.h:520:56: error: unknown type name ‘uint16’
ethercatmain.h:521:54: error: unknown type name ‘uint16’
ethercatmain.h:521:68: error: unknown type name ‘uint16’
ethercatmain.h:522:1: error: unknown type name ‘uint16’
ethercatmain.h:522:43: error: unknown type name ‘uint16’
ethercatmain.h:523:1: error: unknown type name ‘uint16’
ethercatmain.h:523:41: error: unknown type name ‘uint16’
ethercatmain.h:524:1: error: unknown type name ‘uint16’
ethercatmain.h:524:45: error: unknown type name ‘uint16’
ethercatmain.h:524:77: error: unknown type name ‘uint16’
ethercatmain.h:525:39: error: unknown type name ‘uint16’
ethercatmain.h:525:73: error: unknown type name ‘uint8’
ethercatmain.h:527:43: error: unknown type name ‘uint16’
ethercatmain.h:528:1: error: unknown type name ‘uint16’
ethercatmain.h:528:46: error: unknown type name ‘uint16’
ethercatmain.h:528:60: error: unknown type name ‘uint16’
ethercatmain.h:529:41: error: unknown type name ‘uint16’
ethercatmain.h:530:40: error: unknown type name ‘uint16’
ethercatmain.h:531:43: error: unknown type name ‘uint16’
ethercatmain.h:532:41: error: unknown type name ‘uint16’
ethercatmain.h:532:55: error: unknown type name ‘uint8’
ethercatmain.h:533:1: error: unknown type name ‘uint32’
ethercatmain.h:533:46: error: unknown type name ‘uint16’
ethercatmain.h:533:60: error: unknown type name ‘uint16’
ethercatmain.h:534:44: error: unknown type name ‘uint16’
ethercatmain.h:534:58: error: unknown type name ‘uint16’
ethercatmain.h:534:74: error: unknown type name ‘uint16’
ethercatmain.h:535:46: error: unknown type name ‘uint16’
ethercatmain.h:536:43: error: unknown type name ‘uint16’
ethercatmain.h:537:1: error: unknown type name ‘uint64’
ethercatmain.h:537:48: error: unknown type name ‘uint16’
ethercatmain.h:537:62: error: unknown type name ‘uint16’
ethercatmain.h:538:46: error: unknown type name ‘uint16’
ethercatmain.h:538:60: error: unknown type name ‘uint16’
ethercatmain.h:538:76: error: unknown type name ‘uint16’
ethercatmain.h:539:1: error: unknown type name ‘uint64’
ethercatmain.h:539:48: error: unknown type name ‘uint16’
ethercatmain.h:539:66: error: unknown type name ‘uint16’
ethercatmain.h:540:46: error: unknown type name ‘uint16’
ethercatmain.h:540:64: error: unknown type name ‘uint16’
ethercatmain.h:540:80: error: unknown type name ‘uint16’
ethercatmain.h:541:45: error: unknown type name ‘uint16’
ethercatmain.h:541:59: error: unknown type name ‘uint16’
ethercatmain.h:542:1: error: unknown type name ‘uint32’
ethercatmain.h:542:47: error: unknown type name ‘uint16’
ethercatmain.h:543:55: error: unknown type name ‘uint8’
ethercatmain.h:544:58: error: unknown type name ‘uint8’
In file included from oshw.h:29:0,
                 from ethercatbase.c:54:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
ethercatbase.h:54:23: error: unknown type name ‘ecx_portt’
ethercatbase.h:54:53: error: unknown type name ‘uint8’
ethercatbase.h:54:64: error: unknown type name ‘uint8’
ethercatbase.h:54:75: error: unknown type name ‘uint16’
ethercatbase.h:54:87: error: unknown type name ‘uint16’
ethercatbase.h:54:99: error: unknown type name ‘uint16’
ethercatbase.h:55:21: error: unknown type name ‘ecx_portt’
ethercatbase.h:55:51: error: unknown type name ‘uint8’
ethercatbase.h:55:62: error: unknown type name ‘uint8’
ethercatbase.h:55:73: error: unknown type name ‘boolean’
ethercatbase.h:55:87: error: unknown type name ‘uint16’
ethercatbase.h:55:99: error: unknown type name ‘uint16’
ethercatbase.h:55:111: error: unknown type name ‘uint16’
ethercatbase.h:56:13: error: unknown type name ‘ecx_portt’
ethercatbase.h:56:30: error: unknown type name ‘uint16’
ethercatbase.h:56:41: error: unknown type name ‘uint16’
ethercatbase.h:56:52: error: unknown type name ‘uint16’
ethercatbase.h:57:13: error: unknown type name ‘ecx_portt’
ethercatbase.h:57:30: error: unknown type name ‘uint16’
ethercatbase.h:57:41: error: unknown type name ‘uint16’
ethercatbase.h:57:52: error: unknown type name ‘uint16’
ethercatbase.h:58:14: error: unknown type name ‘ecx_portt’
ethercatbase.h:58:31: error: unknown type name ‘uint16’
ethercatbase.h:58:43: error: unknown type name ‘uint16’
ethercatbase.h:58:55: error: unknown type name ‘uint16’
ethercatbase.h:59:14: error: unknown type name ‘ecx_portt’
ethercatbase.h:59:31: error: unknown type name ‘uint16’
ethercatbase.h:59:43: error: unknown type name ‘uint16’
ethercatbase.h:59:55: error: unknown type name ‘uint16’
ethercatbase.h:60:14: error: unknown type name ‘ecx_portt’
ethercatbase.h:60:31: error: unknown type name ‘uint16’
ethercatbase.h:60:43: error: unknown type name ‘uint16’
ethercatbase.h:60:55: error: unknown type name ‘uint16’
ethercatbase.h:61:1: error: unknown type name ‘uint16’
ethercatbase.h:61:18: error: unknown type name ‘ecx_portt’
ethercatbase.h:61:35: error: unknown type name ‘uint16’
ethercatbase.h:61:47: error: unknown type name ‘uint16’
ethercatbase.h:62:14: error: unknown type name ‘ecx_portt’
ethercatbase.h:62:31: error: unknown type name ‘uint16’
ethercatbase.h:62:43: error: unknown type name ‘uint16’
ethercatbase.h:62:55: error: unknown type name ‘uint16’
ethercatbase.h:63:1: error: unknown type name ‘uint16’
ethercatbase.h:63:18: error: unknown type name ‘ecx_portt’
ethercatbase.h:63:35: error: unknown type name ‘uint16’
ethercatbase.h:63:47: error: unknown type name ‘uint16’
ethercatbase.h:64:15: error: unknown type name ‘ecx_portt’
ethercatbase.h:64:32: error: unknown type name ‘uint16’
ethercatbase.h:64:44: error: unknown type name ‘uint16’
ethercatbase.h:64:56: error: unknown type name ‘uint16’
ethercatbase.h:65:14: error: unknown type name ‘ecx_portt’
ethercatbase.h:65:31: error: unknown type name ‘uint16’
ethercatbase.h:65:43: error: unknown type name ‘uint16’
ethercatbase.h:65:55: error: unknown type name ‘uint16’
ethercatbase.h:66:15: error: unknown type name ‘ecx_portt’
ethercatbase.h:66:32: error: unknown type name ‘uint16’
ethercatbase.h:66:44: error: unknown type name ‘uint16’
ethercatbase.h:66:56: error: unknown type name ‘uint16’
ethercatbase.h:67:14: error: unknown type name ‘ecx_portt’
ethercatbase.h:67:31: error: unknown type name ‘uint16’
ethercatbase.h:67:43: error: unknown type name ‘uint16’
ethercatbase.h:67:55: error: unknown type name ‘uint16’
ethercatbase.h:68:13: error: unknown type name ‘ecx_portt’
ethercatbase.h:68:30: error: unknown type name ‘uint32’
ethercatbase.h:68:45: error: unknown type name ‘uint16’
ethercatbase.h:69:13: error: unknown type name ‘ecx_portt’
ethercatbase.h:69:30: error: unknown type name ‘uint32’
ethercatbase.h:69:45: error: unknown type name ‘uint16’
ethercatbase.h:70:13: error: unknown type name ‘ecx_portt’
ethercatbase.h:70:30: error: unknown type name ‘uint32’
ethercatbase.h:70:45: error: unknown type name ‘uint16’
ethercatbase.h:71:15: error: unknown type name ‘ecx_portt’
ethercatbase.h:71:32: error: unknown type name ‘uint32’
ethercatbase.h:71:47: error: unknown type name ‘uint16’
ethercatbase.h:71:74: error: unknown type name ‘uint16’
ethercatbase.h:71:87: error: unknown type name ‘int64’
ethercatsoe.h:71:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatsoe.h:74:4: error: unknown type name ‘uint16’
ethercatsoe.h:79:1: error: unknown type name ‘PACKED_END’
ethercatsoe.h:83:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatsoe.h:83:16: error: redefinition of ‘struct PACKED’
ethercatsoe.h:71:16: note: originally defined here
ethercatsoe.h:86:4: error: unknown type name ‘uint16’
ethercatsoe.h:97:1: error: unknown type name ‘PACKED_END’
ethercatsoe.h:101:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatsoe.h:101:16: error: redefinition of ‘struct PACKED’
ethercatsoe.h:83:16: note: originally defined here
ethercatsoe.h:104:4: error: unknown type name ‘uint16’
ethercatsoe.h:109:1: error: unknown type name ‘PACKED_END’
ethercatsoe.h:126:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
ethercatsoe.h:126:16: error: redefinition of ‘struct PACKED’
ethercatsoe.h:101:16: note: originally defined here
ethercatsoe.h:129:4: error: unknown type name ‘uint32’
ethercatsoe.h:157:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
ethercatsoe.h:158:18: error: unknown type name ‘ecx_contextt’
ethercatsoe.h:158:41: error: unknown type name ‘uint16’
ethercatsoe.h:158:55: error: unknown type name ‘uint8’
ethercatsoe.h:158:70: error: unknown type name ‘uint8’
ethercatsoe.h:158:90: error: unknown type name ‘uint16’
ethercatsoe.h:159:20: error: unknown type name ‘ecx_contextt’
ethercatsoe.h:159:43: error: unknown type name ‘uint16’
In file included from oshw.h:29:0,
                 from ethercatsoe.c:50:
ethercattype.h:68:18: fatal error: osal.h: No such file or directory
compilation terminated.
make: *** [ethercatconfig.o] Error 1

**Comment by mgruhler** [comment]
Readme updated, or rather, a new one added, clarifying thins for ROS...
I consider this fixed :-)
