### ISSUE TITLE
Using soem with robotiq

### ISSUE THREAD

**Issue by jontoto** [mgruhler/soem#8]
I'm trying to build the soem library, but when linking with the robotiq packages I run into an issue where cmake cannot find the soem/ethercattype.h file. It seems like there have been other similar issues with robotiq packages. I'm running on kinetic, is there a way to get them to build together?

**Comment by keerthanamanivannan** [comment]
Did you figure out a way to fix this?

**Comment by newuhe** [comment]
I have the same problem, have you fixed it ???

**Comment by mgruhler** [comment]
How to do this is now documented in the [README.md](https://github.com/mgruhler/soem#Installation).
Please check the section [Development](https://github.com/mgruhler/soem#Development) if you want to use this package from source.
